Lint/AssignmentInCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInLiteral:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/NumericLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - test/**/*

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false
